project:
  type: website

website:
  title: "Personal_Projects"
  navbar:
    left:
      - text: Personal Projects
        menu: 
          - text: Local Indicators of Spatial Association (LISA)
            href: Personal_Proj/LISA/Take-Home_Ex1.html
          - text: Spatial Interaction Model
            href: Personal_Proj/Spatial_Interaction/Take-Home_Ex2.html
    right:
      - href: index.html
        text: Home
      - about.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

