project:
  type: website

website:
  title: "Personal Projects"
  navbar:
    left:
      - text: Personal Projects
        menu: 
          - text: Local Indicators of Spatial Association (LISA)
            href: Personal_Proj/LISA/Take-Home_Ex1.html
          - text: Untangling Fact from Falsehood Using NLP
            href: Personal_Proj/Fake_News_Detection/fake_news.html
    right:
      - href: index.html
        text: Home
      - href: about.html
        text: Contact

format:
  html:
    theme: cosmo
    toc: true

editor: visual

