project:
  type: website

website:
  title: "Phan Hoang Long's Personal Site"
  navbar:
    left:
      - text: Data Analytics Projects
        menu: 
          - text: Analysis of Geospatial Distribution of Bus Ridership by Origin Bus Stop in Singapore
            href: Personal_Proj/LISA/Take-Home_Ex1.html
          - text: Untangling Fact from Falsehood Using NLP
            href: Personal_Proj/Fake_News_Detection/fake_news.html
    right:
      - href: index.html
        text: Home
      - href: about.html
        text: Contact

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

